### ISSUE TITLE
Error on export

### ISSUE THREAD

**Issue by Amaroth** [WowDevTools/Blender-WMO-import-export-scripts#11]
Attempting to export an object as WMO when in vertex paint mode causes an error. The same applies to edit mode and possibly other modes than object mode in general.

**Comment by gratural** [comment]
@skarnproject, when you deal with this issue, dont forget to unhide all hidden objects. Because they leads to the same error.

**Comment by skarnproject** [comment]
It should be fixed. Please, test and confirm. Both editing modes and hidden objects.

**Comment by gratural** [comment]
Not works. On export hidden wmo groups, root wmo has size only 12 bytes. In game model has crash. And i cant export model again by some path, because root wmo are busy - needed Blender restarting.
I dont understand, what for you need debug_utils, because you can just unhide all objects in scene with going to object mode.

**Comment by skarnproject** [comment]
@gratural Debug Utils is a simple wrapper for print() function and just makes debug console output more controllable in terms of adding spacing, headers and such things. It has nothing to do with the current issue.

The export selected issue is happening for me only for root object like portals, fogs or liquids. Working om fixing that.

**Comment by skarnproject** [comment]
Should be fixed in the released Beta version. Please test and confirm.

**Comment by BalkronPainter** [comment]
Fixed.
