### ISSUE TITLE
[Bug] Export error

### ISSUE THREAD

**Issue by Kallar12** [WowDevTools/Blender-WMO-import-export-scripts#5]
https://gyazo.com/d83dbf9991528ec589dd80897581cbc6

a77e48a4440d2ecd341822104546743236e276c6

**Comment by skarnproject** [comment]
What are you exporting? Please supply a blender file. Also make sure it happens on the last commit.

**Comment by Kallar12** [comment]
That was last commit by that time and the wmo i exported worked some commits before

http://workupload.com/file/5kqsKpF

**Comment by gratural** [comment]
@Kallar12, just define settings of your portal. Now as the group parameter indicated her name, not a numeric index. Important: the first group must be indicated that - to which the is turned the front side of the portal.
@skarnproject, Vova can ask you to forced turn off some modes the before exporting, which lead to exporting errors? Like EditMode, VertexPaint mode and unhide all hidden geometry in the scene. Because sometimes if it is forgotten, then getting an error message and have to restart Blender.

**Comment by skarnproject** [comment]
I will make it weird-error safe soon anyway. If the portal is not configured properly, I will raise a properly signed exception. 
@gratural This is actually what I was going to do.

**Comment by Kallar12** [comment]
correct
