### ISSUE TITLE
Fog :(

### ISSUE THREAD

**Issue by gratural** [WowDevTools/Blender-WMO-import-export-scripts#8]
In short, he does not are exported. ((
This applies both as hand-made and re-exported standard WMO (MD_Goldmene, MD_Spidermine) They just not visible in game(in noggit too).
At creation fog, I took settings from Blizzard WMO, and pick in each mesh group name of my placed fog. Maybe i need do something else?

One more thing. When opening fog list, blender shows all scene meshes, not only fog meshes.
http://prntscr.com/eea7dv

**Comment by skarnproject** [comment]
I am already working on the issue. Since some commit fogs are indeed written incorrectly.

Speaking about the list, the technique I used using a callback function to fill a EnumProperty wad apparently bugged. Contents of those fields were moving when a new object was added or something was deleted. I am looking into this, but might actually stay the way it is forever if I don't any workaround.

**Comment by skarnproject** [comment]
Should be fixed as of  https://github.com/WowDevTools/Blender-WMO-import-export-scripts/commit/a7cffadcc0262e1ba6679b724533e49940f90f92. Plesse, test and confirm. This does not include UI fix though, still looking into that.

**Comment by gratural** [comment]
Has no changes, fogs are invisible. My actions:
1. I place fog by button "Add Fog"
2. Change him radius by scaling tool.
3. in each interior group i select him as Fog1
4. Export Wmo
All changing Inner Radius\Farclip\Nearclip has no result

**Comment by skarnproject** [comment]
Works for me. Farclip should be about 20 to see the fog properly.

**Comment by gratural** [comment]
http://prnt.sc/eg78s6
http://i3.kym-cdn.com/photos/images/original/001/043/243/419.gif
